---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T02:21:12Z"
  name: carts-canary
  resourceVersion: "1141162"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 1101c416-1c86-11ea-9ca0-42010a98011e
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
